// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKY2sHSleTg8wQi9MlY-5ifjPlwg-PRJI',
    appId: '1:85812761970:web:ab17511308625ada0139eb',
    messagingSenderId: '85812761970',
    projectId: 'fundriser-app',
    authDomain: 'fundriser-app.firebaseapp.com',
    storageBucket: 'fundriser-app.appspot.com',
    measurementId: 'G-92T19QD662',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL2fBnaoIAuqVWXV2RW0zVFK9z9GnlIck',
    appId: '1:85812761970:android:39fb36e6acad42e20139eb',
    messagingSenderId: '85812761970',
    projectId: 'fundriser-app',
    storageBucket: 'fundriser-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlsj0uywhdkdy0x2gpQ7vBgR51UGgq_Xs',
    appId: '1:85812761970:ios:f5d5b61ba20a4dca0139eb',
    messagingSenderId: '85812761970',
    projectId: 'fundriser-app',
    storageBucket: 'fundriser-app.appspot.com',
    iosBundleId: 'com.example.fundriser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlsj0uywhdkdy0x2gpQ7vBgR51UGgq_Xs',
    appId: '1:85812761970:ios:f5d5b61ba20a4dca0139eb',
    messagingSenderId: '85812761970',
    projectId: 'fundriser-app',
    storageBucket: 'fundriser-app.appspot.com',
    iosBundleId: 'com.example.fundriser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKY2sHSleTg8wQi9MlY-5ifjPlwg-PRJI',
    appId: '1:85812761970:web:6e1d55e8109eefe80139eb',
    messagingSenderId: '85812761970',
    projectId: 'fundriser-app',
    authDomain: 'fundriser-app.firebaseapp.com',
    storageBucket: 'fundriser-app.appspot.com',
    measurementId: 'G-R63L7SZMTR',
  );
}
